# -*- coding: utf-8 -*-
"""practical

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OHM48R2Ou_wsXfuADenNfgx-GaUKO_G
"""

def converter(kg, coef=2.20462):
    return kg * coef

def mysum(a, b):
    return a + b
print (mysum(10,20)

def mysum(a,b):
    return a + b

def power(a):
    return pow(a,2)

def hello_world():
    return "Hello World"

mydict = {'a' : 1, 'b': 2}

mylist = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v','w', 'x', 'y', 'z']
c = mylist[0] + mylist[-1]