# -*- coding: utf-8 -*-
"""2nd.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9GkhjiVy1oI4aYjphi1-gQjwhmKXjo5
"""

x=10
y="10"
z=2.3
sum=x+x
sum1=y+y
sum2=z+z
print(x,y,z,sum,sum1,sum2,type(x),type(y),type(z))