# -*- coding: utf-8 -*-
"""datetime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Dl_F7o-TCj0BHYC5nfpE5oueoZfXOPc
"""

import datetime
datetime.datetime.now()