# -*- coding: utf-8 -*-
"""panda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17VABdZKcCz7iC7zGAFurkOpwVS3zo_av
"""

import numpy as np
import pandas as pd
pd.set_option("display.precision", 2)

df = pd.read_csv('../input/telecom_churn.csv')
df.head()

print(df.shape)

print(df.columns)

print(df.info())

df['Churn'] = df['Churn'].astype('int64')

df.describe()

df.sort_values(by=['Churn', 'Total day charge'],
        ascending=[True, False]).head()