# -*- coding: utf-8 -*-
"""map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17VABdZKcCz7iC7zGAFurkOpwVS3zo_av
"""

from IPython.display import display
import arcgis
from arcgis.gis import GIS

# connect to your GIS
gis = GIS("https://www.arcgis.com","arcgis_python","P@ssword123")

webmap_search = gis.content.search("Ebola maps", item_type="Web Map")
webmap_search

ebola_map_item = webmap_search[1]
ebola_map_item

from arcgis.mapping import WebMap
empty_webmap = WebMap()

empty_webmap.layer

ebola_map = WebMap(ebola_map_item)

for layer in ebola_map.layers:
    print(layer.title)

ebola_map.basemap

ebola_map.definition.spatialReference

dict(ebola_map.definition).keys()

ebola_map

ebola_map.remove_layer(ebola_map.layers[0])

liberia_item = gis.content.get('49161527a2bc4f4782b50d2c14e38f4a')
ebola_map.add_layer(liberia_item, options={'title':'Liberia facilities and hospitals'})

webmap_item_properties = {'title':'Ebola incidents and facilities',
                         'snippet':'Map created using Python API showing locations of Ebola treatment centers',
                         'tags':['automation', 'ebola', 'world health', 'python']}

ebola_map.save(webmap_item_properties, thumbnail='./webmap_thumbnail.png')

webscene_search = gis.content.search("", item_type="Web Scene")
webscene_search

webscene_item = webscene_search[0]
webscene_item

from arcgis.mapping import WebScene
webscene_obj = WebScene(webscene_item)

webscene_obj['operationalLayers']

webscene_obj.keys()

webscene_obj