# -*- coding: utf-8 -*-
"""dic in fuction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h6Q_cH9bAyQ2hdfm6erbDx_-zHB9PKJg
"""

def mean(value):
  if type(value)==dict:
    s=sum(value.values())/len(value)
  else:
    s=sum(value)/len(value)
  return s
p={"m":23,"n":22,"a":20}
u=[1,4,6]
print(mean(u))
print(mean(p))