# -*- coding: utf-8 -*-
"""list in fun.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vITX2aZD_DZycau6gM1jJ17ytQKGOcb
"""

def mean(mylist):
  m=sum(mylist)/len(mylist)
  return m
print(mean([1,2,3,4,5]),type(mean),type(sum))