# -*- coding: utf-8 -*-
"""dic .mean

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9GkhjiVy1oI4aYjphi1-gQjwhmKXjo5
"""

a={'s':1,'b':2,'c':3,'d':4}
m=sum(a.values())
n=len(a)
x=m/n
print(x,m)