# -*- coding: utf-8 -*-
"""idex.append

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Dl_F7o-TCj0BHYC5nfpE5oueoZfXOPc
"""

a=[1,2,9,3,4,5]
a.append(7)
print(a)
q=a.index(3)
print(q)
a.remove(9)
print(a)
a[3:]
a[-2:4]