# -*- coding: utf-8 -*-
"""for.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/163-8fk71mDeOQkGSaB7Kre0DuVVyIJD3
"""

for i in "dhamini":
  print(i.title())

x={'dhamu':23,'lokesh':34,'ashu':56}
for i in x.items():
  print(i)

