# -*- coding: utf-8 -*-
"""while .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VFEq0fTpNLI8iOJKSy6p5BfwVAa3Z031
"""

while True:
  name=input("enter the name")
  if name=="dhamini":
    break
  else:
    continue

def foo(lst):
    return sum([float(i) for i in lst])

foo([1,2,3])