# -*- coding: utf-8 -*-
"""key2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JXd71rRa_4jZ8Bs5Oa6pvBtcgdxHODLv
"""

def foo(d,c):
  return d*c
print(foo(3,4))

def foo(*a):
  a=[x.upper()for x in a]
  return sorted(a)
print(foo("dhamini","acharya"))

