# -*- coding: utf-8 -*-
"""geocoder5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16gkhn-sjvypGSQ1vAIj3gdYBg5rmWlvf
"""

import geopy
import pandas
from geopy.geocoders import Nominatim, GoogleV3

def main():
	io = pandas.read_csv('census-historic-population-borough.csv', index_col=None, header=0, sep=",")

def get_latitude(x):
  return x.latitude

def get_longitude(x):
  return x.longitude

geolocate_column = io['Area_Name'].apply(geolocator.geocode)
  io['latitude'] = geolocate_column.apply(get_latitude)
  io['longitude'] = geolocate_column.apply(get_longitude)
  io.to_csv('geocoding-output.csv')