# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZAIjUj2XeI0uW-tuv2daIq5dIglfjAe
"""

def a(b):
  if b>10:
    return "hot"
  else:
    return "cold"
a(5)

def foo(name):
    return "Hi %s" % name
foo("dhamini")

name=input("enter the name")
surname=input("enter the surname")
s="hi%s%S %(name.tittle(),surname)"
s=f"hello {name}{surname}"
print(s)

def foo(name):
    return "Hi %s" % name.title()
foo('dhamini')