# -*- coding: utf-8 -*-
"""prat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15OHM48R2Ou_wsXfuADenNfgx-GaUKO_G
"""

character='Jon Snow'

print(character)

price=10
print(price)

x = 1
y = 2
z = 3
a = (x * y) ** z / 8
print(a)

a = 1.0
b = 2
sum=int(a+b)
print(sum)

mylist = [1,2,"dhamini"]

name = "John"
print(name[2])

name = "John Smith"
print(name[2:4])

letters = 'abcdefghijklmnopqrstuvwxyz'
print(letters[-2])